#!/usr/bin/env python
import sys, inspect
from cairoStuff import *
from pcb import *
from config import *
import gobject, threading
import time, json
import signal, SocketServer
from collections import deque
import tracking

if demoFrame is not None:
    from tracking import trackingObj as trackingObject

class TrackingSignaller(gobject.GObject):
    def __init__(self):
        self.__gobject_init__()
       
gobject.type_register(TrackingSignaller)
gobject.signal_new("tracking_frame", TrackingSignaller, gobject.SIGNAL_RUN_FIRST,gobject.TYPE_NONE, (str,))

displayQueue = deque([])

class MyTCPHandler(SocketServer.BaseRequestHandler):
    """
    The RequestHandler class for our server.
    It is instantiated once per connection to the server, and must
    override the handle() method to implement communication to the
    client.
    """

    #This is the real handle, the other one is just to test stuff without a real tracking system.
    def handle1(self):
        # self.request is the TCP socket connected to the client
        while(1):
            if len(displayQueue) > 0:
                self.data = displayQueue.popleft()
            else:
                self.data = "null"
            # just send back the same data, but upper-cased
            self.data += '\n'
            self.request.sendall(self.data)
            time.sleep(0.100)


    def handle(self):
        while(1):
            data = {}
            data['positive'] = {'partName':'U3','pad':'3'}
            data['negative'] = {'partName':'U3','pad':'21'}
            data['type'] = 'VDC'
            data['value'] = 5.04
            dataStr = json.dumps(data)
            print dataStr
            self.request.sendall(dataStr)
            time.sleep(0.500)


#Eventually this will be replaced by a event driven system, and the events will be generated by the AutoLoader,PCB, etc stuff
def displayLoop():
    HOST, PORT = "localhost", 9877
    # Create the server, binding to localhost on port 9999
    SocketServer.TCPServer.allow_reuse_address = True
    server = SocketServer.TCPServer((HOST, PORT), MyTCPHandler)
    # Activate the server; this will keep running until you
    # interrupt the program with Ctrl-C
    server.serve_forever()


class AutoLoader(object):
    def __init__(self,gtkWindow):
        self.loadingDict = {
            279:('pcb','funo.brd'),
            211:('selectTool','red'),
            107:('selectTool','green'),
            331:('selectTool','blue'),
        }

        self.objects = {}
        self.window = gtkWindow

        fileName = self.loadingDict[279][1] 
        print "Loading PCB %s"%(fileName,)
        self.pcb = PCB(fileName,displayCallback=self.displayCallback)
        self.pcb.show( )
        window.add(self.pcb)
        
    def processTrackingFrame(self,b,data):
        a = json.loads(data)
        #print 'received trackingFrame',b,a
        if a != {}:
            if tracking.pcb_id in a:
                self.pcb.x = a[tracking.pcb_id]['x'] 
                self.pcb.y = a[tracking.pcb_id]['y']
                self.pcb.rot = a[tracking.pcb_id]['angle'] - self.pcb.rotBias
                self.pcb.rot = 0
            else:
                self.pcb.x = 500
                self.pcb.y = 500
                self.pcb.rot = 00
                        
            if tracking.selectTool_id in a:
                self.pcb.selectTool.activated = True
                self.pcb.selectTool.x = a[tracking.selectTool_id]['x']-12
                self.pcb.selectTool.y = a[tracking.selectTool_id]['y']+12
                a = self.pcb.findModuleUnderMouse(self.pcb.selectTool.x,self.pcb.selectTool.y)
                print a
                if a is not None:
                    self.displayCallback(a)
                    pass
                else:
                    self.selectTool.activated = False
        else:
            self.x = 00
            self.y = 00
            self.rot = 0

    def displayCallback(self,a):
        displayQueue.append(a)


def trackingLoop(sender):
    if demoFrame is  None:
        trackingObject.connect()
    while(1):
        if demoFrame is not None:
            sender.emit("tracking_frame",json.dumps(demoFrame))
        else:
            a = trackingObject.getFrame()
            sender.emit("tracking_frame",json.dumps(a))


if __name__=="__main__":
    window = gtk.Window( )
    window.connect( "delete-event", gtk.main_quit )
    window.set_size_request ( width, height )

    autoLoader = AutoLoader(window)
    trackingSignaller = TrackingSignaller()
    trackingSignaller.connect("tracking_frame",autoLoader.processTrackingFrame)

    trackingThread = threading.Thread(target=trackingLoop,args=(trackingSignaller,))
    trackingThread.start()

    displayThread = threading.Thread(target=displayLoop)
    displayThread.start()

    window.present( )
    gtk.main()

