#!/usr/bin/env python
import sys, inspect
from cairoStuff import *
from sch import *
from config import *
import gobject
import time, json, signal, socket, threading
from displayClient import displayClientObj


class DisplaySignaller(gobject.GObject):
    '''
    This guy just is used to send a gtk signal 
    to the schView about the arrival of a
    new display frame
    '''
    def __init__(self):
        self.__gobject_init__()
       
gobject.type_register(DisplaySignaller)
gobject.signal_new("display_frame", DisplaySignaller, gobject.SIGNAL_RUN_FIRST,gobject.TYPE_NONE, (str,))


class AutoLoader(object):
    def __init__(self,gtkWindow):
        self.loadingDict = {
            279:('sch','funo.sch'),
            211:('selectTool','red'),
            107:('selectTool','green'),
            331:('selectTool','blue'),
        }

        self.objects = {}
        self.window = gtkWindow
        
        fileName = self.loadingDict[279][1] 
        print "Loading PCB %s"%(fileName,)
        self.sch = SCH(fileName,displayCallback=None)
        self.sch.show( )
        window.add(self.sch)

    def processDisplayFrame(self,a,b):
        #print 'processing display frame',a,b
        if b is not '':
            self.sch.processFrame(b)
        

#Eventually this will be replaced by a event driven system, and the events will be generated by the AutoLoader,PCB, etc stuff
def displayClientLoop(sender):
    displayClientObj.connect()
    while(1):
        a = displayClientObj.getFrame()
        sender.emit("display_frame",a)
        

if __name__=="__main__":
    window = gtk.Window( )
    window.connect( "delete-event", gtk.main_quit )
    window.set_size_request ( width, height )
    autoLoader = AutoLoader(window)

    displaySignaller = DisplaySignaller()
    displaySignaller.connect("display_frame",autoLoader.processDisplayFrame)

    displayClientThread = threading.Thread(target=displayClientLoop,args=(displaySignaller,))
    #This guy starts a new thread and polls the displayClient for new display frames."
    displayClientThread.start()

    window.present( )
    gtk.main()

